### ISSUE TITLE
Unable to download Pre-trained-Biaffine-v2.zip

### ISSUE THREAD

**Issue by Meghna-Goyal** [datquocnguyen/BioPosDep#2]
Hello,

I am not able to downlaod the Pre-trained-Biaffine-v2.zip folder from the google drive link mentioned in the readme.md file.

Link: https://drive.google.com/file/d/18IYSJEV0uwbg468lFXejS0Wyw2_8Pjfa/view?usp=sharing
Error: Network Disconnected

Kindly help me with the same.

Regards,
Meghna Goyal

**Comment by datquocnguyen** [comment]
The link still works fine. I am not sure what happened to your side. Try this again: https://drive.google.com/uc?id=18IYSJEV0uwbg468lFXejS0Wyw2_8Pjfa&export=download
